default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  host: localhost

development:
  <<: *default
  database: well_academy_development

test:
  <<: *default
  database: well_academy_test

production:
  <<: *default
  database: well_academy_production
  username: well_academy
  password: <%= ENV['WELL_ACADEMY_DATABASE_PASSWORD'] %>
