default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["HOST"] %>

development:
  <<: *default
  database: well_academy_development

test:
  <<: *default
  database: well_academy_test

production:
  <<: *default
  database: well_academy_production
  username: your_prod_username
  password: <%= ENV["DATABASE_PASSWORD"] %>
