default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: admin
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: well_academy_development

test:
  <<: *default
  database: well_academy_test

production:
  <<: *default
  database: well_academy_production
